version: '3'
services:
  ansible:
    container_name: ansible.local
    build: ./ansible_local
    image: ansible:latest
    volumes:
      - type: bind
        source: ./playbook
        target: /playbook
    tty: true
  sandbox-frontend-01:
    container_name: sandbox-frontend-01.local
    build: ./sandbox
    ports:
      - 80:80
    privileged: true
    tty: true
  sandbox-backend-01:
    container_name: sandbox-backend-01.local
    build: ./sandbox
    privileged: true
    tty: true
